#!/usr/bin/with-contenv bash

# strip leading slash if present in set variable
[[ -n "$CONTEXT_PATH" ]] && CONTEXT_PATH="${CONTEXT_PATH#/}"

# set url base to / if variable not set, readding leading slash if variable is set.
URL_BASE="/${CONTEXT_PATH}"

# add option to pass runtime arguments
IFS=" " read -r -a RUN_ARRAY <<< "$JAVA_OPTS"

cd "${AIRSONIC_ADVANCED_HOME}" || exit

exec \
    s6-setuidgid abc \
    java \
    -Dlog4j2.formatMsgNoLookups=true \
    -Dairsonic.defaultMusicFolder=/music \
    -Dairsonic.defaultPlaylistFolder=/playlists \
    -Dairsonic.defaultPodcastFolder=/podcasts \
    -Dairsonic.home="${AIRSONIC_ADVANCED_SETTINGS}" \
    -Djava.awt.headless=true \
    -Dserver.contextPath="${URL_BASE}" \
    -Dserver.host=0.0.0.0 \
    -Dserver.port=4040 \
    "${RUN_ARRAY[@]}" \
    -jar airsonic.war
